# ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whiteboard-ingress
  namespace: whiteboard
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/websocket-services: "backend-service"
spec:
  rules:
    - host: whiteboard.local
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
          - path: /api/(.*)
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 5000
          - path: /socket.io/(.*)
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 5000
