apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: whiteboard
spec:
  type: NodePort
  selector:
    app: whiteboard-backend
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30657
